# Generated by Django 5.2.7 on 2025-11-08 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_character_image_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='character',
            name='colour',
            field=models.CharField(default='Red', max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='dislikes',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='character',
            name='likes',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
