# Generated by Django 4.2.21 on 2025-11-08 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_character_birthday_character_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
