# Generated by Django 5.2.7 on 2025-10-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
