# Generated by Django 5.2.7 on 2025-10-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(default=None, max_length=1000, unique=True),
        ),
    ]
